name: Lint

on:
  pull_request:
    paths:
      - 'src/**'    

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.14', '1.15', '1.16.x' ]

    steps:      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version}}
      - name: Super-linter
        uses: super-linter/super-linter@v6.2.0  
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#Testing
